jobs:
  Build-Qt-Windows:
    runs-on: windows-2022
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: '6.2.4'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'
on: push
